/*
 * blaqkube MySQL agent
 *
 * Agent used by [blaqkube MySQL operator](http://github.com/blaqkube/mysql-operator) to manage MySQL backup/restore 
 *
 * API version: 0.0.1
 * Contact: contact@blaqkube.io
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

import (
	"encoding/json"
	"net/http"
	"strings"

	"github.com/gorilla/mux"
)

// A MysqlApiController binds http requests to an api service and writes the service results to the http response
type MysqlApiController struct {
	service MysqlApiServicer
}

// NewMysqlApiController creates a default api controller
func NewMysqlApiController(s MysqlApiServicer) Router {
	return &MysqlApiController{ service: s }
}

// Routes returns all of the api route for the MysqlApiController
func (c *MysqlApiController) Routes() Routes {
	return Routes{ 
		{
			"CreateBackup",
			strings.ToUpper("Post"),
			"/backup",
			c.CreateBackup,
		},
		{
			"DeleteBackup",
			strings.ToUpper("Delete"),
			"/backup/{backup}",
			c.DeleteBackup,
		},
		{
			"GetBackupByName",
			strings.ToUpper("Get"),
			"/backup/{backup}",
			c.GetBackupByName,
		},
	}
}

// CreateBackup - create an on-demand backup
func (c *MysqlApiController) CreateBackup(w http.ResponseWriter, r *http.Request) { 
	backup := &Backup{}
	if err := json.NewDecoder(r.Body).Decode(&backup); err != nil {
		w.WriteHeader(500)
		return
	}
	
	apiKey := r.Header.Get("apiKey")
	result, err := c.service.CreateBackup(*backup, apiKey)
	if err != nil {
		w.WriteHeader(500)
		return
	}
	
	EncodeJSONResponse(result, nil, w)
}

// DeleteBackup - Deletes a backup
func (c *MysqlApiController) DeleteBackup(w http.ResponseWriter, r *http.Request) { 
	params := mux.Vars(r)
	backup := params["backup"]
	apiKey := r.Header.Get("apiKey")
	result, err := c.service.DeleteBackup(backup, apiKey)
	if err != nil {
		w.WriteHeader(500)
		return
	}
	
	EncodeJSONResponse(result, nil, w)
}

// GetBackupByName - Get backup properties
func (c *MysqlApiController) GetBackupByName(w http.ResponseWriter, r *http.Request) { 
	params := mux.Vars(r)
	backup := params["backup"]
	apiKey := r.Header.Get("apiKey")
	result, err := c.service.GetBackupByName(backup, apiKey)
	if err != nil {
		w.WriteHeader(500)
		return
	}
	
	EncodeJSONResponse(result, nil, w)
}
