/*
 * blaqkube MySQL agent
 *
 * Agent used by [blaqkube MySQL operator](http://github.com/blaqkube/mysql-operator) to manage MySQL backup/restore 
 *
 * API version: 0.0.1
 * Contact: contact@blaqkube.io
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type S3Credentials struct {

	AwsAccessKeyId string `json:"aws_access_key_id,omitempty"`

	AwsSecretAccessKey string `json:"aws_secret_access_key,omitempty"`

	Region string `json:"region,omitempty"`
}
