/*
 * blaqkube MySQL agent
 *
 * Agent used by [blaqkube MySQL operator](http://github.com/blaqkube/mysql-operator) to manage MySQL backup/restore
 *
 * API version: 0.0.1
 * Contact: contact@blaqkube.io
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

import (
	"time"
)

// Backup - output for a backup request
type Backup struct {
	Identifier string `json:"identifier"`

	Bucket string `json:"bucket"`

	Location string `json:"location"`

	StartTime time.Time `json:"start_time"`

	EndTime *time.Time `json:"end_time,omitempty"`

	// backup status
	Status string `json:"status"`
}
