/*
 * blaqkube MySQL agent
 *
 * Agent used by [blaqkube MySQL operator](http://github.com/blaqkube/mysql-operator) to manage MySQL backup/restore 
 *
 * API version: 0.0.1
 * Contact: contact@blaqkube.io
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

import (
	"time"
)

type Backup struct {

	Location string `json:"location,omitempty"`

	Timestamp time.Time `json:"timestamp,omitempty"`

	S3access S3Info `json:"s3access"`

	// backup status
	Status string `json:"status,omitempty"`

	// keep message in case of an error
	Message string `json:"message,omitempty"`
}
