name: registry
strategies:
  compare-to:
    branch: master
  previous-commit:
    only: master
build: ../.ci/build.sh
scripts:
  bundle: ../.ci/bundle.sh
tag: false
env:
  - name: TAG
    value: quay.io/blaqkube/operators-catalog
