name: registry
strategies:
  compare-to:
    branch: main
  previous-commit:
    only: main
build: ../.circleci/build.sh
scripts:
  bundle: ../.circleci/bundle.sh
tag: false
env:
  - name: TAG
    value: quay.io/blaqkube/operators-catalog
