name: mysql-operator
strategies:
  compare-to:
    branch: master
  previous-commit:
    only: master
build: ./.ci/build.sh
scripts:
  bundle: ./.ci/bundle.sh
tag: false
env:
  - name: VERSION
    value: "0.8.0"
  - name: TAG
    value: quay.io/blaqkube/mysql-controller
