name: mysql-operator
strategies:
  compare-to:
    branch: main
  previous-commit:
    only: main
build: ./.ci/build.sh
scripts:
  bundle: ./.ci/bundle.sh
tag: false
env:
  - name: VERSION
    value: "0.3.0"
  - name: PREVIOUS_VERSION
    value: "0.0.10"
  - name: TAG
    value: quay.io/blaqkube/mysql-controller
