// +build !skippackr
// Code generated by github.com/gobuffalo/packr/v2. DO NOT EDIT.

// You can use the "packr2 clean" command to clean up this,
// and any other packr generated files.
package packrd

import (
	"github.com/gobuffalo/packr/v2"
	"github.com/gobuffalo/packr/v2/file/resolver"
)

var _ = func() error {
	const gk = "011d8aec621f651b250c7bcbbfc36c86"
	g := packr.New(gk, "")
	hgr, err := resolver.NewHexGzip(map[string]string{
		"321a74e0fc0fcfaa57e137ab984e29b2": "1f8b08000000000000ff9c94d16fa24e10c79f7ffc15d3277fe7491dc0369e972672303d4971f76497cbb52f5bb53447a2d22036bdfffe82a0688134399e666767bebbb3f319741da67fc4cc87a7ddfa050cbc342c0037de6669bc80e1255e9a660f9e9314fc78b37b83ffdf86d7ea7af049d3754dd761926cb311ac92e57cf53bd9660000ee3c9b2fe6db68048bd52eca83f47ffaf24c11a5af510aaf51ba8d93cd7fc57534addfbd18a08106089230e6beab9c891dd88ea4400992caf13d62f2663c6e7243b7fff543858044e84b519328fd6d1adcf76de971a61cce1839b9994b34b80f0a577885d65e81d95312b0cb9e87ebc5e0f400ab3a407a53520f9cd1cd787cb4ebb15558e733e208b153c5a031a8f442e6cd4252ce849cbbbcd8b3750fceb7b145e49607e47d67ea8eee2ba5bab3070d81d8f29262e6ab2977f33a0f660f8ece0ee3ca0e25573f6d3f24c5997aa0809f146918efb41897244ab1bd5da815eee21225d1ce2e4da34d7682f163cef163bead3901d992c0b5a5fdcd1604fdee85655a8609de2d302e817e79428a6ebfcc81b23004976eedd09770a4697fbd43b30b40e8b056f80551cd63b58ca1dbcf458688c6f551849813dcffd8c3d56145d55a28a83cb4958573828ab4b397af1efdb405f5ae3735bc19847aee3be26a10d679681eedb6a1ff28ff38d8ad33dfa0d038d66d035fa7f004c0331e0fd8819bff7a97c9fa651565d113241b30d144dd3075cb00331fe011a2f6370000ffff187999f3aa050000",
	})
	if err != nil {
		panic(err)
	}
	g.DefaultResolver = hgr

	func() {
		b := packr.New("dumps", "./dumps")
		b.SetResolver("blue.sql", packr.Pointer{ForwardBox: gk, ForwardPath: "321a74e0fc0fcfaa57e137ab984e29b2"})
	}()
	return nil
}()
