apiVersion: mysql.blaqkube.io/v1alpha1
kind: Store
metadata:
  name: store-sample
spec:
  backend: s3
  s3_backup:
    bucket: bucket-sample
    path: /backup/instance-sample    
    aws_config:
      aws_access_key_id: AKIAXXX
      aws_secret_access_key: aSzx...
      region: eu-west-1
