version: 2
jobs:
  test:
    docker:
      - image: docker:19.03
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Build agent with docker
          command: |
            cd agent
            docker build -t agent .
workflows:
  version: 2
  test_and_build:
    jobs:
      - test
