version: 2
jobs:
  test:
    docker:
      - image: quay.io/blaqkube/docker-gally:b5f01fa76c
    steps:
      - add_ssh_keys:
          fingerprints:
            - "9d:c2:3a:49:b6:9c:b0:20:6e:61:2a:8d:30:fe:20:b4"
      - run:
          name: Clone repository
          command: |
            mkdir -p ~/.ssh
            ssh-keyscan -H github.com >> ~/.ssh/known_hosts
            git clone git@github.com:blaqkube/mysql-operator.git ~/mysql-operator
            git checkout -b ci $CIRCLE_SHA1
      - setup_remote_docker
      - run:
          name: Build agent with docker
          command: |
            cd ~/mysql-operator/agent
            VERSION=$(git log -1 --pretty='format:%H' . |cut -c1-10)
            docker login -u $DOCKER_USER -p $DOCKER_PASSWORD quay.io
            docker build -t quay.io/blaqkube/mysql-agent:$VERSION .
            docker push quay.io/blaqkube/mysql-agent:$VERSION
            cd ../mysql-operator
            VERSION=$(git log -1 --pretty='format:%H' . |cut -c1-10)
            docker build -t quay.io/blaqkube/mysql-operator:$VERSION .
            docker push quay.io/blaqkube/mysql-operator:$VERSION
  build:
    machine: true
    steps:
      - checkout
      - run:
          name: Start Kubernetes
          command: |
            pwd && ls
            if grep false .circleci/integration; then
                exit 0;
            fi
            docker run -d --name kube --privileged -p 8443:8443 -p 10080:10080 bsycorp/kind:v1.17.9
            until curl -s --fail http://127.0.0.1:10080/kubernetes-ready; do
              sleep 1;
            done
            echo "Kubernetes ready - run tests!"
workflows:
  version: 2
  test_and_build:
    jobs:
      - test:
          context: QUAY
