apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: users.mysql.blaqkube.io
spec:
  group: mysql.blaqkube.io
  names:
    kind: User
    listKind: UserList
    plural: users
    singular: user
  scope: Namespaced
  versions:
  - name: v1alpha1
    schema:
      openAPIV3Schema:
        description: User is the Schema for the users API
        properties:
          apiVersion:
            description: 'APIVersion defines the versioned schema of this representation
              of an object. Servers should convert recognized schemas to the latest
              internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
            type: string
          kind:
            description: 'Kind is a string value representing the REST resource this
              object represents. Servers may infer this from the endpoint the client
              submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
            type: string
          metadata:
            type: object
          spec:
            description: UserSpec defines the desired state of User
            properties:
              grants:
                items:
                  properties:
                    accessMode:
                      type: string
                    database:
                      type: string
                  required:
                  - database
                  type: object
                type: array
              instance:
                description: 'INSERT ADDITIONAL SPEC FIELDS - desired state of cluster
                  Important: Run "operator-sdk generate k8s" to regenerate code after
                  modifying this file Add custom validation using kubebuilder tags:
                  https://book-v1.book.kubebuilder.io/beyond_basics/generating_crd.html'
                type: string
              password:
                type: string
              username:
                type: string
            required:
            - instance
            - password
            - username
            type: object
          status:
            description: UserStatus defines the observed state of User
            properties:
              conditions:
                items:
                  description: ConditionStatus provide details about the observed
                    conditions
                  properties:
                    lastProbeTime:
                      format: date-time
                      type: string
                    message:
                      type: string
                    status:
                      type: string
                  type: object
                type: array
              lastCondition:
                description: 'INSERT ADDITIONAL STATUS FIELD - define observed state
                  of cluster Important: Run "operator-sdk generate k8s" to regenerate
                  code after modifying this file Add custom validation using kubebuilder
                  tags: https://book-v1.book.kubebuilder.io/beyond_basics/generating_crd.html'
                type: string
            type: object
        type: object
    served: true
    storage: true
    subresources:
      status: {}
