apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: stores.mysql.blaqkube.io
spec:
  group: mysql.blaqkube.io
  names:
    kind: Store
    listKind: StoreList
    plural: stores
    singular: store
  scope: Namespaced
  versions:
  - name: v1alpha1
    schema:
      openAPIV3Schema:
        description: Store is the Schema for the stores API
        properties:
          apiVersion:
            description: 'APIVersion defines the versioned schema of this representation
              of an object. Servers should convert recognized schemas to the latest
              internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
            type: string
          kind:
            description: 'Kind is a string value representing the REST resource this
              object represents. Servers may infer this from the endpoint the client
              submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
            type: string
          metadata:
            type: object
          spec:
            description: StoreSpec defines the desired state of Store
            properties:
              backend:
                enum:
                - s3
                type: string
              s3access:
                description: S3Info defines the S3 bucket, path and connection
                properties:
                  awsConfig:
                    description: S3Credentials defines the credentials to connect
                      to S3
                    properties:
                      aws_access_key_id:
                        type: string
                      aws_secret_access_key:
                        type: string
                      region:
                        type: string
                    required:
                    - aws_access_key_id
                    - aws_secret_access_key
                    - region
                    type: object
                  bucket:
                    type: string
                  path:
                    type: string
                required:
                - bucket
                type: object
            required:
            - backend
            type: object
          status:
            description: StoreStatus defines the observed state of Store
            properties:
              conditions:
                items:
                  description: ConditionStatus provide details about the observed
                    conditions
                  properties:
                    lastProbeTime:
                      format: date-time
                      type: string
                    message:
                      type: string
                    status:
                      type: string
                  type: object
                type: array
              lastCondition:
                description: 'INSERT ADDITIONAL STATUS FIELD - define observed state
                  of cluster Important: Run "operator-sdk generate k8s" to regenerate
                  code after modifying this file Add custom validation using kubebuilder
                  tags: https://book-v1.book.kubebuilder.io/beyond_basics/generating_crd.html'
                type: string
            required:
            - lastCondition
            type: object
        type: object
    served: true
    storage: true
    subresources:
      status: {}
