apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: stores.mysql.blaqkube.io
spec:
  group: mysql.blaqkube.io
  names:
    kind: Store
    listKind: StoreList
    plural: stores
    singular: store
  scope: Namespaced
  subresources:
    status: {}
  validation:
    openAPIV3Schema:
      description: Store is the Schema for the stores API
      properties:
        apiVersion:
          description: 'APIVersion defines the versioned schema of this representation
            of an object. Servers should convert recognized schemas to the latest
            internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
          type: string
        kind:
          description: 'Kind is a string value representing the REST resource this
            object represents. Servers may infer this from the endpoint the client
            submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
          type: string
        metadata:
          type: object
        spec:
          description: StoreSpec defines the desired state of Store
          type: object
        status:
          description: StoreStatus defines the observed state of Store
          type: object
      type: object
  version: v1alpha1
  versions:
  - name: v1alpha1
    served: true
    storage: true
