# This kustomization.yaml is not intended to be run by itself,
# since it depends on service name and namespace that are out of this kustomize package.
# It should be run by config/default
resources:
- bases/mysql.blaqkube.io_backups.yaml
- bases/mysql.blaqkube.io_stores.yaml
- bases/mysql.blaqkube.io_instances.yaml
- bases/mysql.blaqkube.io_users.yaml
- bases/mysql.blaqkube.io_databases.yaml
- bases/mysql.blaqkube.io_grants.yaml
- bases/mysql.blaqkube.io_chats.yaml
- bases/mysql.blaqkube.io_operations.yaml
# +kubebuilder:scaffold:crdkustomizeresource

patchesStrategicMerge:
# [WEBHOOK] To enable webhook, uncomment all the sections with [WEBHOOK] prefix.
# patches here are for enabling the conversion webhook for each CRD
#- patches/webhook_in_backups.yaml
#- patches/webhook_in_stores.yaml
#- patches/webhook_in_instances.yaml
#- patches/webhook_in_users.yaml
#- patches/webhook_in_databases.yaml
#- patches/webhook_in_grants.yaml
#- patches/webhook_in_chats.yaml
#- patches/webhook_in_operations.yaml
# +kubebuilder:scaffold:crdkustomizewebhookpatch

# [CERTMANAGER] To enable webhook, uncomment all the sections with [CERTMANAGER] prefix.
# patches here are for enabling the CA injection for each CRD
#- patches/cainjection_in_backups.yaml
#- patches/cainjection_in_stores.yaml
#- patches/cainjection_in_instances.yaml
#- patches/cainjection_in_users.yaml
#- patches/cainjection_in_databases.yaml
#- patches/cainjection_in_grants.yaml
#- patches/cainjection_in_chats.yaml
#- patches/cainjection_in_operations.yaml
# +kubebuilder:scaffold:crdkustomizecainjectionpatch

# the following config is for teaching kustomize how to do kustomization for CRDs.
configurations:
- kustomizeconfig.yaml
