/*
 * blaqkube MySQL agent
 *
 * Agent used by [blaqkube MySQL operator](http://github.com/blaqkube/mysql-operator) to manage MySQL backup/restore
 *
 * API version: 0.0.1
 * Contact: contact@blaqkube.io
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package service

import openapi "github.com/blaqkube/mysql-operator/agent/go"

// Router defines the required methods for binding the api requests to a responses for the MysqlApi
// The Router implementation should parse necessary information from the http request,
// pass the data to a Servicer to perform the required actions, then write the service results to the http response.
type Router interface {
	Routes() openapi.Routes
}
