/*
 * blaqkube MySQL agent
 *
 * Agent used by [blaqkube MySQL operator](http://github.com/blaqkube/mysql-operator) to manage MySQL backup/restore
 *
 * API version: 0.0.1
 * Contact: contact@blaqkube.io
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package agent

// User struct for User
type User struct {
	Username string  `json:"username"`
	Password string  `json:"password"`
	Grants   []Grant `json:"grants,omitempty"`
}
