# permissions for end users to edit chats.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: chat-editor-role
rules:
- apiGroups:
  - mysql.blaqkube.io
  resources:
  - chats
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - mysql.blaqkube.io
  resources:
  - chats/status
  verbs:
  - get
