# permissions for end users to view grants.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: grant-viewer-role
rules:
- apiGroups:
  - mysql.blaqkube.io
  resources:
  - grants
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - mysql.blaqkube.io
  resources:
  - grants/status
  verbs:
  - get
