# permissions for end users to edit grants.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: grant-editor-role
rules:
- apiGroups:
  - mysql.blaqkube.io
  resources:
  - grants
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - mysql.blaqkube.io
  resources:
  - grants/status
  verbs:
  - get
