# permissions for end users to view operations.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: operation-viewer-role
rules:
- apiGroups:
  - mysql.blaqkube.io
  resources:
  - operations
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - mysql.blaqkube.io
  resources:
  - operations/status
  verbs:
  - get
