
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - ""
  resources:
  - configmaps
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - ""
  resources:
  - pods
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - apps
  resources:
  - statefulsets
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - mysql.blaqkube.io
  resources:
  - backups
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - mysql.blaqkube.io
  resources:
  - backups/finalizers
  verbs:
  - update
- apiGroups:
  - mysql.blaqkube.io
  resources:
  - backups/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - mysql.blaqkube.io
  resources:
  - chats
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - mysql.blaqkube.io
  resources:
  - chats/finalizers
  verbs:
  - update
- apiGroups:
  - mysql.blaqkube.io
  resources:
  - chats/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - mysql.blaqkube.io
  resources:
  - databases
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - mysql.blaqkube.io
  resources:
  - databases/finalizers
  verbs:
  - update
- apiGroups:
  - mysql.blaqkube.io
  resources:
  - databases/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - mysql.blaqkube.io
  resources:
  - grants
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - mysql.blaqkube.io
  resources:
  - grants/finalizers
  verbs:
  - update
- apiGroups:
  - mysql.blaqkube.io
  resources:
  - grants/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - mysql.blaqkube.io
  resources:
  - instances
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - mysql.blaqkube.io
  resources:
  - instances/finalizers
  verbs:
  - update
- apiGroups:
  - mysql.blaqkube.io
  resources:
  - instances/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - mysql.blaqkube.io
  resources:
  - stores
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - mysql.blaqkube.io
  resources:
  - stores/finalizers
  verbs:
  - update
- apiGroups:
  - mysql.blaqkube.io
  resources:
  - stores/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - mysql.blaqkube.io
  resources:
  - users
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - mysql.blaqkube.io
  resources:
  - users/finalizers
  verbs:
  - update
- apiGroups:
  - mysql.blaqkube.io
  resources:
  - users/status
  verbs:
  - get
  - patch
  - update
