
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - mysql.blaqkube.io
  resources:
  - backups
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - mysql.blaqkube.io
  resources:
  - backups/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - mysql.blaqkube.io
  resources:
  - databases
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - mysql.blaqkube.io
  resources:
  - databases/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - mysql.blaqkube.io
  resources:
  - instances
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - mysql.blaqkube.io
  resources:
  - instances/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - mysql.blaqkube.io
  resources:
  - stores
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - mysql.blaqkube.io
  resources:
  - stores/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - mysql.blaqkube.io
  resources:
  - users
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - mysql.blaqkube.io
  resources:
  - users/status
  verbs:
  - get
  - patch
  - update
