name: agent
strategies:
  compare-to:
    branch: master
  previous-commit:
    only: master
build: ../.circleci/build.sh
scripts:
  bundle: ../.circleci/bundle.sh
tag: false
env:
  - name: TAG
    value: quay.io/blaqkube/mysql-agent

