/*
 * blaqkube MySQL agent
 *
 * Agent used by [blaqkube MySQL operator](http://github.com/blaqkube/mysql-operator) to manage MySQL backup/restore
 *
 * API version: 0.0.1
 * Contact: contact@blaqkube.io
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package main

import (
	"flag"
	"fmt"
	"log"
	"net/http"
	"os"

	openapi "github.com/blaqkube/mysql-operator/agent/go"
	"github.com/blaqkube/mysql-operator/agent/service"
	"github.com/blaqkube/mysql-operator/agent/service/backup"
)

func main() {
	boolPtr := flag.Bool("restore", false, "restore the database from store")
	flag.Parse()
	if *boolPtr {
		log.Printf("Restore database...")
		filename := os.Getenv("FILENAME")
		bucket := os.Getenv("BUCKET")
		filePath := os.Getenv("FILEPATH")
		if filePath == "" || bucket == "" || filename == "" {
			fmt.Println("Missing parameter, check FILENAME, BUCKET and FILEPATH are set")
			os.Exit(1)
		}
		err := backup.PullS3File(filename, bucket, filePath)
		if err != nil {
			fmt.Printf("Error while reading s3://%s%s: %v\n", bucket, filePath, err)
			os.Exit(1)
		}
		return
	}
	log.Printf("Create exporter user")
	err := backup.CheckDb("root@tcp(localhost:3306)/", 20)
	if err != nil {
		fmt.Printf("Error checking database: %v\n", err)
		os.Exit(1)
	}
	err = backup.CreateExporter("root@tcp(localhost:3306)/")
	if err != nil {
		fmt.Printf("Error create user: %v\n", err)
		os.Exit(1)
	}

	log.Printf("Server started")

	MysqlApiController := service.NewMysqlApiController()

	router := openapi.NewRouter(MysqlApiController)

	log.Fatal(http.ListenAndServe(":8080", router))
}
