/*
 * blaqkube MySQL agent
 *
 * Agent used by [blaqkube MySQL operator](http://github.com/blaqkube/mysql-operator) to manage MySQL backup/restore
 *
 * API version: 0.0.1
 * Contact: contact@blaqkube.io
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package main

import (
	"flag"
	"log"
	"net/http"

	openapi "github.com/blaqkube/mysql-operator/agent/go"
	service "github.com/blaqkube/mysql-operator/agent/service"
)

func main() {
	boolPtr := flag.Bool("restore", false, "restore the database from store")
	flag.Parse()
	if *boolPtr {
		log.Printf("Restore database...")
		filename := os.Getenv("FILENAME")
		bucket := os.Getenv("BUCKET")
		filePath := os.Getenv("FILEPATH")
		if filePath == "" || bucket == "" || filename == "" {
			fmt.Println("Missing parameter, check FILENAME, BUCKET and FILEPATH are set"
			os.Exit(1)
		}
		err := service.PullS3File(filename, bucket, filePath)
		if err != nil {
			os.Exit(1)
		}
		return
	}

	log.Printf("Server started")

	MysqlApiService := service.NewMysqlApiService()
	MysqlApiController := service.NewMysqlApiController(MysqlApiService)

	router := openapi.NewRouter(MysqlApiController)

	log.Fatal(http.ListenAndServe(":8080", router))
}
