scorecard:
  output: json
  plugins:
    - basic:
        cr-manifest:
          - "deploy/crds/mysql.blaqkube.io_v1alpha1_instance_cr.yaml"
    - olm:
        cr-manifest:
          - "deploy/crds/mysql.blaqkube.io_v1alpha1_instance_cr.yaml"
        csv-path: "deploy/olm-catalog/mysql-operator/manifests/mysql-operator.clusterserviceversion.yaml"
